tasks:
  - command: |
      brew install aws-vault
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
      sudo mv ./awscliv2.zip /bin
      sudo unzip /bin/awscliv2.zip -d /bin
      sudo /bin/aws/install
      aws-vault add default --backend=file 
      aws-vault open 
      aws-vault login default --backend=file 
github:
  prebuilds:
    master: true