tasks:
  - name: Setup environment variables
    command: |
      source ./setup-env-variables.sh
      gp sync-done env-setup
  - name: Install AWS CLI
    command: |
      gp sync-await env-setup
      ./install-aws-cli.sh
      gp sync-done aws-cli
  - name: Setup default aws-vault & Open Dashboards
    command: |
      gp sync-await aws-cli
      ./collect-credentials.sh
      ./open-cloud-dashboards.sh
  - name: Install kubectl
    command: source ./install-kubectl.sh
  - name: Install Terraform
    command: source ./install-terraform.sh

github:
  prebuilds:
    master: true
